// export const GET_BILLING_OVERVIEW = 'GET_BILLING_DATA';
// export const GET_BILLING_OVERVIEW_FAILED = 'GET_BILLING_OVERVIEW_FAILED';
// export const GET_BILLING_OVERVIEW_SUCCEEDED = 'GET_BILLING_OVERVIEW_SUCCEEDED';
export const GET_REPOS_STATUS_SUCCEEDED = 'GET_REPOS_STATUS_SUCCEEDED';
export const FETCH_STARRRED_STATUS = 'FETCH_STARRRED_STATUS';

export default {
  // GET_BILLING_OVERVIEW,
  // GET_BILLING_OVERVIEW_FAILED,
  // GET_BILLING_OVERVIEW_SUCCEEDED,
  FETCH_STARRRED_STATUS,
};
